project:
  type: book
  output-dir: docs

book:
  title: "Reinstein's template for Quarto (WIP)"
  author: "David Reinstein"
  repo-url: https://github.com/daaronr/dr_quarto_template/
  execute:
    warning: false
    message: false
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/summary.qmd
    - references.qmd
  reader-mode: true

comments:
    hypothesis: true

bibliography: references.bib

format:
  html:
    code-fold: true
    code-link: true #note: this isn't working for me
    code-tools: true
    theme: cosmo
    citations-hover: true
    footnotes-hover: true

 # pdf:
  #  documentclass: scrreprt
  #


#editor: visual

